config/routes.rb
Rails.application.routes.draw do
  get 'news/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
  	resources :news, only: [:index]
  	get 'news/show', to: 'news#show'
  end

  resources :news, only: [:index]
  get 'news/show', to: 'news#show'
  get 'news/get_topic', to: 'news#get_topic'

  root to: 'news#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include JsonResponse
  include ExceptionHandler
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  private

  def render_error(error, status)
    json_response({ message: error[:message], description: error[:description] }, status)
  end
end

app/controllers/concerns/json_response.rb
module JsonResponse
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    return unless request.xhr?

    @data = News::FetchNewsService.call(params[:url])
  end

  def show
    return unless request.xhr?

    @data = News::GetTopicService.call(params[:topic])
  end

  def get_topic
    @data = News::GetTopicService.call(params[:url])
    render json: @data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/_items.html.slim
- @data[:items].each do |item|
  .col-md-2.item-col
    = link_to news_show_path(topic: item[:link]), class: 'link-item-cell' do
      .item-cell
        strong= item[:title]
        i= item[:link_note]
        .item-image
          .spinner-border.text-success.item-image-spinner role='status' data-link="#{item[:link]}"
            span.sr-only Loading...
        i= item[:votes]

app/views/news/_topic.html.slim
.row
  .col-md-12.loading-col
    img.topic-img src="#{@data[:image]}"
  .col-md-12
    h2= @data[:title]
  .col-md-12= @data[:content].html_safe

app/views/news/index.html.slim
.container#item-list-container
  .row#item-list-row
  .row.loading-col
    .col-md-12
      .spinner-border.text-success role='status'
        span.sr-only Loading...
  .row.more-col.hide
    .col-md-12= link_to t('views.news.index.more'), 'javascripts:;', class: 'btn btn-info more-link'

= javascript_pack_tag 'news'

app/views/news/index.js.erb
$('.loading-col').hide();
$('#item-list-row').append("<%= j (render('items')) %>");
'<% if @data[:more].present? %>'
  $('.more-col').removeClass('hide');
'<% else %>'
  $('.more-col').addClass('hide');
'<% end %>'

$('.item-image-spinner').each(function(index, obj){
  $.ajax({
    url: Routes.news_get_topic_path(),
    dataType: 'json',
    type: 'GET',
    data: {url: $(this).data('link')},
    success: function(response){
      $(obj).parent().html("<img src='" + response.image + "' alt='topic_image' class='topic-image'>");
    },
    fail: function(jqXHR, textStatus, errorThrown ){
      $(obj).parent().html("<img src='' alt='topic_image' class='topic-image'>");
    }
  });
})

app/views/news/show.html.slim
.container#topic
  .row
    .col-md-12
      strong.back-btn
      = link_to t('views.news.show.back'), root_path
  .row.loading-col
    .col-md-12
      .spinner-border.text-success role='status'
        span.sr-only Loading...

= javascript_pack_tag 'show'

app/views/news/show.js.erb
$('.loading-col').hide();
$('#topic').append("<%= j (render('topic')) %>");